name: XSS Scout

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Your website URL"
        required: true
        type: string

jobs:
  run-xss-scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        working-directory: agents
        run: npm install

      - name: Run XSS agent
        working-directory: agents
        run: npm run xss
        env:
          TARGET_URL: ${{ inputs.target_url }}

      - name: Show report
        working-directory: agents
        run: cat xss-report.txt