name: XSS Scout

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Your website URL"
        required: true
        type: string

jobs:
  run-xss-scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run XSS agent
        working-directory: agents
        run: node xss-scout.js
        env:
          TARGET_URL: ${{ inputs.target_url }}

      - name: Show report
        working-directory: agents
        run: cat xss-report.txt